// Auto-generated by datalink-extcore columnar bridge macro.
// This is a stub — the real bridge is generated by `datalink_extcore::__columnar_bridge_conv!`
// in the main lib.rs when building against the ducklink monorepo.

// In the ducklink monorepo, the `datalink_extcore::__columnar_bridge_conv!`
// macro generates the appropriate colvec <-> row adapter functions
// (__bridge_colvecs_to_rows, __bridge_vals_to_colvec, etc.) based on
// the types module and column_types module provided.

// For standalone verification without the monorepo, use:
//   cargo build --target wasm32-wasip2  # checks syntax and imports
// The full component build requires:
//   cargo component build --target wasm32-wasip2 --release
